-- Records that a member checked "I have read and agree to the Terms of
-- Service, Privacy Policy, Community Rules, and Security & Privacy" at
-- signup -- which exact version of those four pages they saw, and when.
-- This is a consent record, not a public-facing feature: nobody (not even
-- the member themselves) can read these two columns back through the API --
-- see part 3. The only way to look them up is the Supabase dashboard's
-- Table Editor / SQL editor, the same "trusted root" path already used
-- elsewhere in this app (see 004_restrict_role_visibility.sql).
--
-- Run this in the Supabase SQL editor AFTER 011_signup_age_gate.sql.
-- Safe to run even if some of this already exists.

-- 1. The columns -------------------------------------------------------------
-- Added nullable first, backfilled for any accounts that already exist
-- (created before this migration ran -- there's no real consent record for
-- those, so they're stamped with an honest placeholder rather than a fake
-- one), THEN switched to not null. Because the default is dropped again
-- right after backfilling, it does NOT quietly apply to new signups going
-- forward -- an insert that omits either column now fails outright, which
-- is exactly the point: it's what stops handle_new_user() below from ever
-- creating a profile without both, even for a request that bypassed this
-- app's own UI and called Supabase directly.

alter table public.profiles add column if not exists legal_docs_version text;
alter table public.profiles add column if not exists legal_docs_accepted_at timestamptz;

update public.profiles
  set legal_docs_version = 'unrecorded-pre-migration'
  where legal_docs_version is null;

update public.profiles
  set legal_docs_accepted_at = created_at
  where legal_docs_accepted_at is null;

alter table public.profiles alter column legal_docs_version set not null;
alter table public.profiles alter column legal_docs_accepted_at set not null;

-- 2. Wire it into signup ------------------------------------------------------
-- app/actions.ts sends legal_docs_version and legal_docs_accepted_at as
-- signup metadata (the same mechanism already used for username) once
-- someone's checked the consent box on the signup form -- the timestamp is
-- generated by the server, not trusted from the browser.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, legal_docs_version, legal_docs_accepted_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'legal_docs_version',
    (new.raw_user_meta_data ->> 'legal_docs_accepted_at')::timestamptz
  );
  return new;
end;
$$;

-- (Trigger itself already exists from schema.sql and doesn't need
-- recreating -- it just calls whichever version of this function is
-- current.)

-- 3. Keep it out of the public API -------------------------------------------
-- Same pattern as the role column in 004_restrict_role_visibility.sql --
-- the row-level "Profiles are publicly readable" policy stays as-is (so
-- usernames etc. still work), this just removes these two specific columns
-- from what anon/authenticated can ever select.

revoke select (legal_docs_version, legal_docs_accepted_at) on public.profiles
  from anon, authenticated;
